# Generated by Django 5.0.6 on 2024-05-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_tipo_de_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='tipo_de_pago',
        ),
        migrations.AddField(
            model_name='venta',
            name='pago_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='pago_puntos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='pago_tarjeta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
