# Generated by Django 5.0.6 on 2024-05-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codigo',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
