# Generated by Django 5.0.6 on 2024-08-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
