# Generated by Django 5.0.6 on 2024-08-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_apellidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='puntos_pase_heroclix',
            field=models.IntegerField(default=0),
        ),
    ]
