# Generated by Django 5.0.6 on 2024-08-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customuser_puntos_pase_heroclix'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='puntos_heroclix',
            field=models.IntegerField(default=0),
        ),
    ]
