# Generated by Django 5.0.6 on 2024-11-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_customuser_correo_arena_customuser_konami_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tag', models.CharField(choices=[('pokemon', 'Pokémon'), ('yu_gi_oh', 'Yu-Gi-Oh'), ('magic', 'Magic')], max_length=20)),
            ],
        ),
    ]
