# Generated by Django 5.0.6 on 2024-05-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='articulo',
            field=models.CharField(default='artículo', max_length=255),
        ),
    ]
