# Generated by Django 5.0.6 on 2024-08-04 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios', '0002_intercambio_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
